export const URL_HOME = "/"
export const URL_LOGIN = "/connexion"
export const URL_SUBSCRIBE = "/inscription"
export const URL_CONFIRM_ORDER = "/confirmation/commande"
export const URL_ADD_ITEM = "/ajout/item"